### PR TITLE
Support S3 prefix configuration

### PR DESCRIPTION
**Pull request by nicl**
The code already supports various options to configure S3 uploads, but they aren't accessible to the end developer! And I'd really like to use them.

### CODE REVIEW

**Comment by sihil** [comment]
Yes - let's do that. Can you make the parameter naming match those in the S3 type where it is exposed? (See https://github.com/guardian/deploy/blob/master/magenta-lib/src/main/scala/magenta/deployment_type/S3.scala#L19-L24)

**Comment by nicl** [comment]
@sihil done!

**Comment by philwills** [comment]
Looks good. Do you want some help going through how to test and roll this out?

**Comment by nicl** [comment]
@philwills yeah that would be useful actually. I don't want to break Riff Raff and ruin everyone's day!

**Comment by nicl** [comment]
@philwills @sihil Tested this on CODE, though not thoroughly, and appears to work.

**Comment by sihil** [comment]
:+1: Want to push it out yourself?

**Pull request merged**
