### PR TITLE
Recursively list all the autoscaling groups

### PR DESCRIPTION
**Pull request by alexduf**

### CODE REVIEW

**Comment by sihil** [comment]
This LGTM :+1:

**Comment by alexduf** [comment]
Unfortunately I get a StackOverflow. I'll try another fix. The aws API documentation isn't crystal clear.

**Comment by alexduf** [comment]
Stackoverflow is fixed, tests are fixed. Do you mind having another look @sihil ?

**Comment by sihil** [comment]
Be nice to have a test that exercises the nextToken logic, but otherwise :+1:

**Pull request merged**
