### PR TITLE
Template for RiffRaff S3 buckets

### PR DESCRIPTION
**Pull request by philwills**
Includes expiration policy and IAM groups and policies.

Note that I haven't yet tried actually running this.

### CODE REVIEW

**Comment by sihil** [comment]
Looks fine - only question is the motivation for expiring objects? Are simply objects discarded after 14 days? Does that mean it's impossible to deploy something older than 14 days?

**Comment by philwills** [comment]
The artifact bucket doesn't have a lifecycle policy, only those for metadata.  Those dropping away will mean they aren't in auto-completes after a restart, but you should still be able to deploy as the artifact will still be there.

**Comment by philwills** [comment]
I think this should address your concerns @sihil

**Comment by sihil** [comment]
I am now very happy :bowtie: :+1:

**Pull request merged**
