### PR TITLE
Allow riffraff uploads for identity account

### PR DESCRIPTION
**Pull request by jamespamplin**
Grant access to identity account for uploading to riffraff S3 buckets.

### CODE REVIEW

**Comment by markjamesbutler** [comment]
:+1:

**Comment by philwills** [comment]
Bonus points for fixing the ropey indenting @obrienm left behind.

**Comment by jamespamplin** [comment]
Thanks @philwills

**Comment by philwills** [comment]
Now applied.

**Comment by jamespamplin** [comment]
Verified, works a treat. Thanks again.

**Pull request merged**
