### PR TITLE
[CONTROVERSIAL] Remove build pinning logic

### PR DESCRIPTION
**Pull request by philwills**
I just can't take them any more.

The pins must die!

### CODE REVIEW

**Comment by sihil** [comment]
The websys in me is genuinely concerned about the less loved projects that are deployed infrequently as TeamCity only keeps artifacts for a fortnight and then they are gone. Possibly this is the scarring from the time we couldn't roll back the Content API because of exactly this.

**Comment by philwills** [comment]
Oh god, I'm going to end up writing a teamcity project, aren't I?

**Comment by philwills** [comment]
Oh god, I'm going to end up writing a teamcity plugin, aren't I?

**Comment by philwills** [comment]
Having shown by masochistic tendencies by writing a teamcity plugin (https://github.com/guardian/teamcity-s3-plugin), I'm going to close this.

**Pull request closed without merging**
